name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-test:
    runs-on: macos-latest  # MacOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # или нужная версия

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt || pip install flake8 isort black mypy pytest

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 .

      - name: Run isort
        run: |
          source venv/bin/activate
          isort --diff --check .

      - name: Run black check
        run: |
          source venv/bin/activate
          black --check .

      - name: Run mypy
        run: |
          source venv/bin/activate
          mypy .

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest
